## NumPy

**`NumPy`** es una librería utilizada para el manejo de arreglos (arrays) y matrices multidimensionales, cuenta con múltiples funciones para trabajar con estos objetos. Una matriz en **`NumPy`** es una cuadricula de valores, todos del mismo tipo e indexados.

```python
import numpy as np
```

In [4]:
import numpy as np

In [5]:
lista = [1, 2, 3]

In [6]:
type(lista)

list

In [7]:
# Usando np.array() podemos castear una lista a un objeto numpy.ndarray
type(np.array(lista))

numpy.ndarray

### Arreglos (arrays) de 1 dimensión (vector).

| Método           | Atributo   |
|------------------|------------|
|**`.argmin()`**   |**`.dtype`**|
|**`.argmax()`**   |**`.ndim`** |
|**`.cumsum()`**   |**`.size`** |
|**`.cumprod()`**  |**`.shape`**|
|**`.dot()`**      | **`.T`**   |
|**`.flatten()`**  |            |
|**`.max()`**      |            |
|**`.min()`**      |            |
|**`.mean()`**     |            |
|**`.reshape()`**  |            |
|**`.transpose()`**|            |
|**`.sum()`**      |            |
|**`.sort()`**     |            |
|**`.tolist()`**   |            |

In [8]:
vector = [-2, 4, 1, 3.5]

vector = np.array(vector)

vector

array([-2. ,  4. ,  1. ,  3.5])

In [9]:
# .argmin() y .argmax() retornan el indice del minimo y del maximo respectivamente
print(vector.argmin())
print(vector.argmax())

0
1


In [10]:
# .cumsum() y cumprod() retorna un np.array() con la suma acumulada y el producto acumulado respectivamente

print(vector.cumsum())
print(vector.cumprod())

[-2.   2.   3.   6.5]
[ -2.  -8.  -8. -28.]


In [11]:
# .reshape() cambia la "forma" de la matriz

matriz_1 = vector.reshape(1, 4)

matriz_1

array([[-2. ,  4. ,  1. ,  3.5]])

In [12]:
# .transpose() hace la transpuesta de la matriz, también se puede usar .T

print(matriz_1.transpose())

print("-"*20)

print(matriz_1.T)

[[-2. ]
 [ 4. ]
 [ 1. ]
 [ 3.5]]
--------------------
[[-2. ]
 [ 4. ]
 [ 1. ]
 [ 3.5]]


In [13]:
# .tolist() retorna el array en una lista

matriz_1.tolist()

[[-2.0, 4.0, 1.0, 3.5]]

In [14]:
list(matriz_1)

[array([-2. ,  4. ,  1. ,  3.5])]

In [15]:
vector

array([-2. ,  4. ,  1. ,  3.5])

In [16]:
matriz_1

array([[-2. ,  4. ,  1. ,  3.5]])

In [17]:
# .flatten() retorna un vector plano con los elementos de la matriz

matriz_1.flatten()

array([-2. ,  4. ,  1. ,  3.5])

In [18]:
# .sort() ordena la matriz de menor a mayor, lo hace in-place

print("Antes de .sort()", vector)

vector.sort()

print("Después de .sort()", vector)

Antes de .sort() [-2.   4.   1.   3.5]
Después de .sort() [-2.   1.   3.5  4. ]


In [19]:
vector

array([-2. ,  1. ,  3.5,  4. ])

In [20]:
# .ndim retorna el número de dimensiones

vector.ndim

1

In [21]:
# .size retorna el número de elementos

vector.size

4

In [22]:
# .shape retorna en una tupla las dimesiones de la matriz

vector.shape

(4,)

In [23]:
# .dtype retorna el tipo de dato de los elementos de la matriz

vector.dtype

dtype('float64')

### Arreglos (arrays) de 2 dimensiones (matrices).

Comparte los métodos y atributos de los vectores por que son de la misma clase.

Existen varias funciones para inicializar matrices o arrays:

| Función                  | Descripción                                                                             |
|--------------------------|-----------------------------------------------------------------------------------------|
|**`np.empty((n, m))`**    | Inicializa una matriz **nxm** vacia.                                                    |
|**`np.zeros((n, m))`**    | Inicializa una matriz **nxm** de ceros.                                                 |
|**`np.ones((n, m))`**     | Inicializa una matriz **nxm** de unos.                                                  |
|**`np.eye(n)`**           | Inicializa la matriz identidad de orden **n**.                                          |
|**`np.identity(n)`**      | Inicializa la matriz identidad de orden **n**.                                          |
|**`np.full(shape, elem)`**| Inicializa una matriz con la forma de **`shape`** usando los elementos de **`elem`**.   |
|**`np.linspace(a, b, p)`**| Inicializa un array de **`p`** elementos entre **`a`** y **`b`**, todos **x-distantes**.|

In [24]:
matriz = np.array([[1, 2, 3, 10], 
                   [4, 5, 6, 20], 
                   [7, 8, 9, 30]])

matriz

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

In [25]:
print(matriz)

[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]


In [26]:
matriz.flatten()

array([ 1,  2,  3, 10,  4,  5,  6, 20,  7,  8,  9, 30])

In [27]:
matriz.reshape(6, 2)

array([[ 1,  2],
       [ 3, 10],
       [ 4,  5],
       [ 6, 20],
       [ 7,  8],
       [ 9, 30]])

In [28]:
# Aunque muestre numeros dentro de la matriz, np.empty() la inicializa vacia, estos números que se ven
# Estan en memoria y numpy los usa para mostrar la matriz

empty = np.empty(shape = (5, 5), dtype = "float")

print(empty)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 9.34605715e-307
  8.01106038e-307]
 [7.56603881e-307 1.42419938e-306 7.56603881e-307 8.45603440e-307
  3.56043054e-307]
 [1.60219306e-306 6.23059726e-307 1.06811422e-306 3.56043054e-307
  1.37961641e-306]
 [9.45697982e-308 8.01097889e-307 1.78020169e-306 7.56601165e-307
  1.02359984e-306]
 [1.33510679e-306 2.22522597e-306 6.23053614e-307 9.34608432e-307
  2.56765117e-312]]


In [29]:
# Inicializa una matriz de 1's.

ones = np.ones(shape = (5, 5), dtype = "int8")

print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [30]:
# Inicializa una matriz de 0's.

zeros = np.zeros(shape = (5, 5), dtype = "int8")

print(zeros)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [31]:
# Matriz identidad

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
# np.full() crea una lista con forma "shape" y la llena con un iterable.

full = np.full(shape = (5, 5), fill_value = range(5))

print(full)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [33]:
# np.linspace(a, b, p) crea un array de "p" elementos entre "a" y "b", todos x-distantes

linspace = np.linspace(1, 12, 16)

print(linspace)

[ 1.          1.73333333  2.46666667  3.2         3.93333333  4.66666667
  5.4         6.13333333  6.86666667  7.6         8.33333333  9.06666667
  9.8        10.53333333 11.26666667 12.        ]


### Slicing en NumPy

En Python para hacer slicing de una lista de listas debiamos escribir primero la "fila" y de segundo la "columna" asi:
```python
lista[a][b]
```

Usando un **`np.array()`** podemos usar la siguiente notación:
```python
array[a, b]
```

Incluso, podemos pasar un **slicing** dentro del **slicing** para filtrar aun más los datos:
```python
array[a1 : a2, b1 : b2]
```

También podemos hacer **indexing** dentro del **slicing**

```python
array[[a1, a3], [b2, b4]]
```

In [34]:
matriz = np.array([[1, 0, 0, 0, 0], [0, 0, 2, 0, 0], [1, 1, 0, 0, 1], [2, 1, 1, 1, 0], [1, 2, 1, 2, 2]])

print(matriz)

[[1 0 0 0 0]
 [0 0 2 0 0]
 [1 1 0 0 1]
 [2 1 1 1 0]
 [1 2 1 2 2]]


In [62]:
dimension = matriz.ndim
dimension

2

In [35]:
# Hacer

matriz[4][1]

2

In [36]:
# Es igual que hacer

matriz[4, 1]

2

In [37]:
# Slicing
matriz[1:4, 1:4]

array([[0, 2, 0],
       [1, 0, 0],
       [1, 1, 1]])

In [38]:
# Slicing + Indexing

matriz[[1, 3], [2, 4]]

array([2, 0])

### Operaciones con Arrays

In [39]:
A = np.array([[20, 40], [30, 50]])
B = np.array([[4, 5], [2, 3]])

print(A)
print("-"*20)
print(B)

[[20 40]
 [30 50]]
--------------------
[[4 5]
 [2 3]]


In [40]:
# Suma

A + B

array([[24, 45],
       [32, 53]])

In [41]:
# Resta
A - B

array([[16, 35],
       [28, 47]])

In [42]:
# Multiplicación por escalar

A * 5

array([[100, 200],
       [150, 250]])

In [43]:
# Multiplicación elemento a elemento (no es la forma matemática de multiplicar)

A * B

array([[ 80, 200],
       [ 60, 150]])

In [44]:
# División por escalar

A / 5

array([[ 4.,  8.],
       [ 6., 10.]])

In [45]:
# Producto de matrices (también conocido como producto de vectorial)

A.dot(B)

array([[160, 220],
       [220, 300]])

In [46]:
print(A)
print("-"*20)
print(B)

[[20 40]
 [30 50]]
--------------------
[[4 5]
 [2 3]]


#### Concatenar

In [47]:
# Concatenar verticalmente

np.concatenate((A, B), axis = 0)

array([[20, 40],
       [30, 50],
       [ 4,  5],
       [ 2,  3]])

In [48]:
# Concatenar horizontalmente

np.concatenate((A, B), axis = 1)

array([[20, 40,  4,  5],
       [30, 50,  2,  3]])

### Números aleatorios en NumPy

|Función                             |Descripción                                                                                                                                         |
|------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------|
|**`np.random.random(n)`**           | Genera un número aleatorio entre 0 y 1, si damos el parametro **`n`** genera una lista de **`n`** elementos aleatorios entre 0 y 1, solo genera vectores.                                                                                                                       |
|**`np.random.rand(shape)`**         | Genera un array de forma **shape** con números aleatorios entre 0 y 1.                                                                             |
|**`np.random.randn(shape)`**        | Genera un array de forma **shape** con números aleatorios entre -1 y 1.                                                                           |
|**`no.random.randint(a, b, size)`** | Genera un array de tamaño **size** con numeros enteros aleatorios entre **a** y **b**.                                                             |
|**`np.random.choice(obj, size, p)`**| Genera un array de tamaño **size** con los elementos de **obj**, se le pueden dar pesos a los elementos usando **p**, retorna elementos repetidos.|
|**`np.random.seed(n)`**             | Genera una semilla.                                                                                                                                 |
|**`np.random.RandomState(n)`**      | Genera una semilla.                                                                                                                                 |

In [49]:
np.random.random(size = (5, 5))

array([[0.3544102 , 0.49086535, 0.65145098, 0.52640091, 0.56975228],
       [0.04191724, 0.90881773, 0.46660888, 0.46605319, 0.5422092 ],
       [0.7544436 , 0.59349714, 0.41857573, 0.77895015, 0.52159124],
       [0.47210364, 0.4344529 , 0.32647105, 0.50325945, 0.89932836],
       [0.82279791, 0.83473386, 0.55136156, 0.07000084, 0.08333143]])

In [50]:
print(np.random.random())

print("-"*30)

print(np.random.random(5))

0.5093742536882544
------------------------------
[0.65962172 0.07627396 0.23243038 0.25876255 0.02997695]


In [51]:
print(np.random.rand())

print("-"*30)

print(np.random.rand(2, 3))

0.11630318209052704
------------------------------
[[0.73988037 0.61034682 0.55853548]
 [0.38241565 0.64024475 0.8725487 ]]


In [52]:
print(np.random.randn())

print("-"*30)

print(np.random.randn(2, 3))

0.16766446955597702
------------------------------
[[ 0.46698616 -0.13637005  0.05303795]
 [ 0.38795619 -0.51852489 -1.40002099]]


In [53]:
print(np.random.randint(0, 10))

print("-"*30)

print(np.random.randint(1, 10, size = [5, 5]))

9
------------------------------
[[4 6 8 8 4]
 [7 7 1 8 8]
 [8 4 2 3 3]
 [3 8 2 8 1]
 [4 6 6 6 5]]


In [54]:
print(np.random.choice(["a", "e", "i", "o", "u"], size = 10, p = [0.6, 0.1, 0.1, 0.1, 0.1])) 

['a' 'a' 'a' 'i' 'a' 'a' 'a' 'a' 'a' 'a']


In [55]:
for i in range(5):
    np.random.seed(4)
    print(np.random.randn())

0.05056170714293955
0.05056170714293955
0.05056170714293955
0.05056170714293955
0.05056170714293955


In [56]:
for i in range(4):
    rs = np.random.RandomState(2)
    print(rs.rand())
    print(rs.randint(0, 10))
    print(np.random.randn()) # No usa rs
    print("-"*30)    

0.43599490214200376
8
0.499951333237829
------------------------------
0.43599490214200376
8
-0.9959089311068651
------------------------------
0.43599490214200376
8
0.6935985082913116
------------------------------
0.43599490214200376
8
-0.41830152002691007
------------------------------


In [57]:
np.random.seed(15)

for i in range(4):
    print(np.random.rand())
    print(np.random.randint(0, 10))
    print(np.random.randn())
    print("-"*30)  

0.8488176972685787
5
-0.15590853388271336
------------------------------
0.27540092860641197
5
-0.5017896732977485
------------------------------
0.02495303232907431
1
-0.9021190404034566
------------------------------
0.8724294447722278
4
0.6891445632908499
------------------------------


In [58]:
# Código para establecer el número de decimales (Cambiar {0:0.2f} para elegir el número de decimales)

np.set_printoptions(formatter = {"float" : lambda x: "{0:0.2f}".format(x)})

np.random.randn(6, 6)

array([[3.02, 0.12, -0.04, 0.27, 0.52, 0.84],
       [-0.39, 0.28, 1.10, -0.46, -0.37, -0.22],
       [-0.13, -1.55, -1.23, -1.46, -0.85, 1.30],
       [1.22, 0.35, 0.27, 1.07, 0.54, 0.90],
       [-0.83, -0.39, 0.45, 0.94, 0.59, 1.56],
       [-0.06, -1.26, 0.88, 0.71, -0.65, -0.45]])

In [59]:
np.random.randn(6, 6)

array([[-0.15, -0.42, 0.68, -0.73, 0.79, -0.07],
       [-0.74, -0.30, 0.21, 0.25, -0.69, -1.03],
       [0.70, 2.22, -0.25, 0.47, -1.19, 0.36],
       [0.64, 1.98, -0.34, -2.02, 0.16, -0.63],
       [1.59, 0.84, -0.56, -0.43, 0.34, -1.03],
       [1.48, -1.21, -0.24, -1.81, 0.14, -0.42]])

In [60]:
np.empty((5, 5), dtype = "float64")

array([[0.35, 0.49, 0.65, 0.53, 0.57],
       [0.04, 0.91, 0.47, 0.47, 0.54],
       [0.75, 0.59, 0.42, 0.78, 0.52],
       [0.47, 0.43, 0.33, 0.50, 0.90],
       [0.82, 0.83, 0.55, 0.07, 0.08]])

si alguna vez poniendo la ruta del archivo y te da un error de Unicode xxxxx o algo así se arregla pd.read_excel(r"C: con la r esa antes de las comillas X

In [61]:
################################################################################################################################